Controllers/RestaurantsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SGV_Booking.Data;

namespace SGV_Booking.Controllers
{
    public class RestaurantsController : Controller
    {
        const string SessionUserId = "_UserID";
        const string SessionUserName = "_UserName";

        private readonly SGVContext _context;

        public RestaurantsController(SGVContext context)
        {
            _context = context;
        }
        private IActionResult GetRestaurantView(string restaurantName)
        {
            var restaurant = _context.Restaurants
                                      .Include(r => r.RestaurantAddress)
                                      .Include(r => r.RestaurantOpenDay)
                                      .Include(r => r.RestaurantOpenTimes)
                                      .FirstOrDefault(r => r.RestaurantName == restaurantName);
            if (restaurant == null)
            {
                return NotFound();
            }
            return View(restaurant);
        }

        public IActionResult Bamboo() => GetRestaurantView("Bamboo Leaf");
        public IActionResult La_oeste() => GetRestaurantView("La Oeste De La Mar");
        public IActionResult Mexikana() => GetRestaurantView("Mexikana");

    }
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SGV_Booking.Data;
using SGV_Booking.Models;
using SGV_Booking.ViewModels;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;


namespace SGV_Booking.Controllers
{
    public class UsersController : Controller
    {
        const string SessionUserId = "_UserID";
        const string SessionUserName = "_UserName";
        private readonly SGVContext _context;

        public UsersController(SGVContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            return _context.Users != null ?
                        View(await _context.Users.ToListAsync()) :
                        Problem("Entity set 'SGVDatabaseContext.Users'  is null.");
        }

        [HttpGet]
        public async Task<IActionResult> RestaurantIndex(int id)
        {
            var vm = new RestaurantAndBookings();
            if (id == null || _context.Users == null)
            {
                Console.WriteLine("test");
                return NotFound();
            }
            vm.TheUsers = await _context.Users.ToListAsync();
            vm.TheRestaurant = await _context.Restaurants.FirstOrDefaultAsync(m => m.RestaurantId == id);
            vm.TheBanquets = await _context.Banquets.ToListAsync();
            vm.RestaurantBookings = await _context.Bookings
                .Where(i => i.RestaurantId == id)
                .OrderBy(i => i.BookingTime)
                .ToListAsync();

            if (vm.TheRestaurant == null)
            {
                return NotFound();
            }

            return View(vm);

        }

        [HttpPost]
        public async Task<IActionResult> RestaurantIndex(int id, int? RestaurantRewardValue)
        {
            if (RestaurantRewardValue.HasValue)
            {
                var restaurant = await _context.Restaurants.FirstOrDefaultAsync(m => m.RestaurantId == id);
                if (restaurant != null)
                {
                    restaurant.RestaurantRewardValue = RestaurantRewardValue.Value;
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToAction("RestaurantIndex", new { id = id });
        }


        // GET: Users/RestaurantBookingDetails/10004
        public async Task<IActionResult> RestaurantBookingDetails(int id)
        {
            var vm = new BookingBanquetUser();

            if (id == null || _context.Bookings == null)
            {
                return NotFound();
            }

            vm.TheBooking = await _context.Bookings.FirstOrDefaultAsync(i => i.BookingId == id);
            vm.TheBanquet = await _context.Banquets.FirstOrDefaultAsync(i => i.BanquetId == vm.TheBooking.BanquetOption);
            vm.TheUser = await _context.Users.FirstOrDefaultAsync(i => i.UserId == vm.TheBooking.CustomerId);
            vm.TheRestaurant = await _context.Restaurants.FirstOrDefaultAsync(i => i.RestaurantId == vm.TheBooking.RestaurantId);
            if (vm.TheBooking == null)
            {
                return NotFound();
            }

            return View(vm);
        }


        public async Task<IActionResult> CustomerIndex(UsersAndBookings vm, int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            vm.TheUser = await _context.Users.FirstOrDefaultAsync(m => m.UserId == id);
            vm.UserBookings = await _context.Bookings
                .Where(i => i.CustomerId == id)
                .Include(i => i.Restaurant)
                .OrderBy(i => i.BookingTime)
                .ToListAsync();

            vm.rewardValues = _context.Restaurants.Select(r => r.RestaurantRewardValue).ToList();

            if (vm.TheUser == null)
            {
                return NotFound();
            }

            return View(vm);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CustomerIndex(int id, UsersAndBookings vm)
        {
            Console.WriteLine(id);
            Console.WriteLine(vm.TheUser.UserId);

            Console.WriteLine(vm.TheUser.FirstName);

            if (id != vm.TheUser.UserId)
            {
                return NotFound();
            }


            Console.WriteLine("Im here 0");
            try
            {
                _context.Update(vm.TheUser);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                Console.WriteLine("It caught an error");
                if (!UserExists(vm.TheUser.UserId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            vm.TheUser = await _context.Users.FirstOrDefaultAsync(m => m.UserId == id);
            vm.UserBookings = await _context.Bookings
                .Where(i => i.CustomerId == id)
                .Include(i => i.Restaurant)
                .ToListAsync();

            Console.WriteLine("Im here 1");
            return View(vm);

            Console.WriteLine("Im here 2");
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register([Bind("UserID, FirstName, LastName, PhoneNumber, Email, Password")] User user)
        {
            ViewBag.phoneError = null;
            ViewBag.emailError = null;
            ViewBag.firstName = user.FirstName;

            if (ModelState.IsValid)
            {
                var registerQuery = _context.Users
                    .Where(userindata => userindata.PhoneNumber.Equals(user.PhoneNumber) || userindata.Email.Equals(user.Email))
                    .Select(userindata => userindata)
                    .ToList();

                if (!user.Email.Contains("@"))
                {
                    ViewBag.emailError = "Incorrect Format - e.g name@example.com";
                }

                if (!user.PhoneNumber.All(char.IsDigit) || user.PhoneNumber.Length < 10)
                {
                    ViewBag.phoneError = "Invalid Phone Number - e.g. 0123456789";
                }

                if (registerQuery.Count == 0 && user.Email.Contains("@") && user.PhoneNumber.All(char.IsDigit) && user.PhoneNumber.Length == 10)
                {
                    user.UserType = 2;
                    user.BookingsCount = 0;
                    _context.Add(user);
                    await _context.SaveChangesAsync();

                    // Send a confirmation email
                    await SendConfirmationEmail(user);

                    return RedirectToAction(nameof(RegisterDetails));
                }

                if (registerQuery.Count > 0)
                {
                    var userEmailAndPassword = await _context.Users
                        .FirstOrDefaultAsync(userindata => userindata.PhoneNumber.Equals(user.PhoneNumber) || userindata.Email.Equals(user.Email));

                    if (userEmailAndPassword.PhoneNumber == user.PhoneNumber)
                    {
                        ViewBag.phoneError = "Phone number is already in use.";
                    }
                    if (userEmailAndPassword.Email == user.Email)
                    {
                        ViewBag.emailError = "Email is already in use.";
                    }
                }
            }

            return View();
        }

        // Send confirmation email method
        private async Task SendConfirmationEmail(User user)
        {
            try
            {
                var fromEmail = "bookingsgv@outlook.com"; // Replace with your email address
                var fromEmailPassword = "test3456";
                var toEmail = user.Email;
                var subject = "Registration Confirmation";
                var body = $@"Dear {user.FirstName},<br><br>
Thank you for registering with us! Your account has been created successfully.<br><br>
Sincerely,<br>
SGV Team";

                using (var smtpClient = new SmtpClient("smtp.office365.com")) // Replace with your email provider's SMTP server
                {
                    smtpClient.Port = 587; // Replace with the SMTP server port of your email provider
                    smtpClient.Credentials = new NetworkCredential(fromEmail, fromEmailPassword);
                    smtpClient.EnableSsl = true;

                    var mailMessage = new MailMessage(fromEmail, toEmail, subject, body);
                    mailMessage.IsBodyHtml = true;

                    await smtpClient.SendMailAsync(mailMessage);
                }
            }
            catch (Exception ex)
            {
                // Handle email sending errors
                Console.WriteLine("Email sending error: " + ex.ToString());
            }
        }

        public IActionResult RegisterDetails()
        {
            return View();
        }


        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login([Bind("Email, Password")] User user)
        {
            ViewBag.noLogin = null;

            //If the enters their login, then they are sent to the index page.
            ViewBag.num = null;
            if (!string.IsNullOrWhiteSpace(user.Email))
            {
                //If user input is in the database.
                var login = _context.Users

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor
@{

}
<!DOCTYPE html>
<html class="h-100" lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SGV_Booking</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SGV_Booking.styles.css" asp-append-version="true" />
</head>
<body class="d-flex flex-column h-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/SGVlogo.png" alt="" height="72">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 ps-3 pe-3">
                        <li class="nav-item ps-3 pe-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <div class="dropdown ps-3 pe-3">
                            <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" style="background-color:transparent; border-color:white; margin-top:0.1rem">
                                Restaurants
                            </button>
                            <ul class="dropdown-menu ms-3">
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Bamboo">Bamboo Leaf</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="La_oeste">La Oeste De La Mar</a></li>
                                <li><a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Mexikana">Mexikana</a></li>
                            </ul>
                        </div>
                        <li class="nav-item ps-3 pe-3">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Booking" asp-action="Bookingselection">Make a booking</a>
                        </li>
                    </ul>
                </div>
                <nav class="navbar navbar-light">
                    <p class="mt-3">
                        Welcome, @if (HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") == null || HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") == -1)
                        {
                            <p class="mt-3">&nbsp;User!</p>
                        }
                        else
                        {
                            <p class="mt-3">&nbsp;@HttpContextAccessor?.HttpContext?.Session.GetString("_UserName")!</p>
                        }
                    </p>
                    <div class="btn-group dropstart ps-3">
                        <button type="button" class="btn btn-outline-primary navbar-brand mx-auto" aria-expanded="false" data-bs-toggle="dropdown">
                            <img src="/images/hamburger_icon.svg" alt="">
                        </button>
                        <ul class="dropdown-menu mt-5">
                            <li class="nav-item">
                                @if (HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") == null || HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") == -1)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                                }
                                else if (HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") < 10000)
                                {
                                    <a class="nav-link text-dark" asp-action="RestaurantIndex" asp-controller="Users" asp-route-id="@HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID")">Dashboard</a>
                                }
                                else if (HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") > 9999)
                                {
                                    <a class="nav-link text-dark" asp-action="CustomerIndex" asp-controller="Users" asp-route-id="@HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID")">Dashboard</a>
                                }
                            </li>
                            <li class="nav-item">
                                @if (HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") == null || HttpContextAccessor?.HttpContext?.Session.GetInt32("_UserID") == -1)
                                {
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
                                }
                                else
                                {
                                    <a class="nav-link text-dark" asp-action="Logout" asp-controller="Users">Logout</a>
                                }
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer mt-auto py-3" style="background-color:white">
        <div class="container">
            <p>Soylent Green Ventures © 2023. All Rights Reserved. | Designed by Team T</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>